[package]
name = "btf2llvm"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
inkwell = { version = "0.5", features = ["llvm14-0-force-static"] }

[profile.release]
lto = "fat"
panic = "abort"
